-- Antes de correr, crear una base de datos con nombre 'hospital'
--- creamos un usuario que pueda trabajar en la tabla
CREATE DATABASE visa_petitions;
CREATE USER uservpetitions@'%' IDENTIFIED BY '12345678';
CREATE DATABASE staging;

GRANT ALL PRIViLEGES ON staging.* TO uservpetitions@'%';

GRANT ALL PRIViLEGES ON visa_petitions.* TO uservpetitions@'%';
--- 
USE visa_petitions;

DROP TABLE IF EXISTS Petitions;
CREATE TABLE Petitions (
  CASE_NUMBER VARCHAR(18) NOT NULL,
  CASE_STATUS VARCHAR(30) NOT NULL,
  EMPLOYER_ID INTEGER NOT NULL,
  JOB_TITLE VARCHAR(30) NOT NULL,
  FULL_TIME_POSITION VARCHAR(1) NOT NULL,
  PREVAILING_WAGE FLOAT(10,2) NOT NULL,
  YEAR INTEGER NOT NULL,
  LOC_ID INTEGER NOT NULL,
  SOC_CODE VARCHAR(7) NOT NULL,
  CONSTRAINT pk_petitions PRIMARY KEY(CASE_NUMBER),
  CONSTRAINT fk_Petitions_Employers_EMPLOYER_ID FOREIGN KEY(EMPLOYER_ID) REFERENCES Employers(EMPLOYER_ID),
  CONSTRAINT fk_Petitions_Cities_states_LOC_ID FOREIGN KEY(LOC_ID) REFERENCES Cities_states(LOC_ID),
  CONSTRAINT fk_Petitions_SOC_SOC_CODE FOREIGN KEY(SOC_CODE) REFERENCES SOC(SOC_CODE)
);

DROP TABLE IF EXISTS Cities_states;
CREATE TABLE Cities_states (
    LOC_ID INTEGER PRIMARY KEY NOT NULL,
    CITY VARCHAR(60) NOT NULL,
    STATE VARCHAR(60) NOT NULL
);

DROP TABLE IF EXISTS Employers;
CREATE TABLE Employers (
  EMPLOYER_ID INTEGER PRIMARY KEY NOT NULL,
  EMPLOYER_NAME VARCHAR(30) NOT NULL
);


DROP TABLE IF EXISTS SOC;
CREATE TABLE SOC (
  SOC_CODE VARCHAR(7) PRIMARY KEY NOT NULL,
  SOC_NAME VARCHAR(100) NOT NULL
);